### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/obuilder#109]
This is a tracking issue (and will likely be updated) for getting OBuilder running with FreeBSD.

## Motivation

FreeBSD on x86 is a Tier 1 supported architecture for OCaml. We should support all Tier 1 architectures for CI systems where technically possible. Adding FreeBSD support for OBuilder would allow the [CI systems]((https://github.com/ocurrent/overview)) maintained by CI team to work on that platform. Additional efforts to support macos and Windows are currently in progress.

## Scope 

- [x] Implement and test the ZFS on FreeBSD. Current ZFS implementation is being used on macos and has been validated but not currently used, on Linux. Existing ZFS modules are being used across macOS and FreeBSD. 
- [x] Implement obuilder sandbox model, either using Jails/user isolation directly on FreeBSD, or the runj OCI implementation https://github.com/samuelkarp/runj. Used jails directly https://github.com/ocurrent/obuilder/pull/174
- [x] OCluster worker integration for FreeBSD, produce OCaml binaries on FreeBSD that are deployable to the cluster. Setup via ansible in https://github.com/ocurrent/freebsd-infra
- [x] Document the technical architecture of OBuilder on FreeBSD
- [x] Technical blog post about FreeBSD OBuilder support (IN PROGRESS)
- [x] Setup stress tests for FreeBSD OBuilder, opam-health-check used to stress test the FreeBSD pool.
- [x] Setup CI for FreeBSD OBuilder, included in ocaml-ci builds.
- [x] Deploy FreeBSD OBuilder as an OCluster worker and setup test pool for testing higher level applications like (https://github.com/ocurrent/ocaml-ci/pull/856), health check and (https://github.com/ocurrent/opam-repo-ci/pull/230).
- [x] Get a baseline for FreeBSD ocluster-worker to size up a suitable server to run it on.

**Comment by hannesm** [comment]
Great that there's some work on FreeBSD support. A minor note about the document @dustanddreams (feel free to reach out to me if you want to discuss FreeBSD & OCaml & opam things): you can just `pkg install ocaml-opam` -- I maintain this port, and going that path will also work on arm64 and 32 bit systems (there are some patches needed for the opam-full tarball).

**Comment by dustanddreams** [comment]
> Great that there's some work on FreeBSD support. A minor note about the document @dustanddreams (feel free to reach out to me if you want to discuss FreeBSD & OCaml & opam things): you can just `pkg install ocaml-opam` -- I maintain this port, and going that path will also work on arm64 and 32 bit systems (there are some patches needed for the opam-full tarball).

Oh, thanks, I was not aware of an `ocaml-opam` package, and had found the hard way that the `ocaml` package is way out of date and unsuitable for recent opam.

**Comment by hannesm** [comment]
@dustanddreams thanks for your work on this. I'm curious whether you tried the devel/ocaml-opam FreeBSD package instead of downloading the 2.1.4 (sic) full tarball yourself? If you run into issues with the devel/ocaml-opam port, please let me know -- since I'm happy to look into these. [NB: this may reduce your stage1 to "opam init -y -a bare ; opam switch create 4.14.1"]

**Comment by kit-ty-kate** [comment]
@hannesm in a CI setting I would rather use upstream opam rather than any of the distribution's. This way we control what version it should be (e.g. on Linux we use opam master in opam-repo-ci) and are alerted much quicker if there are issues in opam itself.

**Comment by hannesm** [comment]
> @hannesm in a CI setting I would rather use upstream opam rather than any of the distribution's. This way we control what version it should be (e.g. on Linux we use opam master in opam-repo-ci) and are alerted much quicker if there are issues in opam itself.

As you like, but please note according to the document linked above, the opam tarball used is 2.1.4, while the package is 2.1.5. I honestly would use the distributers opam (unless it is very old) since this is what most people use. I'd as well sync the installation / OCaml installation guidelines with what CI is using (i.e. on old systems, please download opam from ... ; on more up-to-date systems, install opam from the system package manager).

But as written above, you're in charge of the opam repo CI.

**Comment by tmcgilchrist** [comment]
An initial run of opam-health-check against FreeBSD 13.2 for OCaml 4.14 is available on http://freebsd-health-check.ocamllabs.io:8080. We plan to add a temporary health-check instance just for FreeBSD 4.14 and 5.0 to run semi-regularly until more packages are supported or constrained away in opam-repository.

**Comment by tmcgilchrist** [comment]
Closing as completed. FreeBSD support is available in the cluster and applications like opam-repo-ci and ocaml-ci are using it.
