### ISSUE TITLE
macOS failure

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/obuilder#112]
cc @mtelvers 
```
Building on mac-mon-2
[...]
/: (copy (src .) (dst opam-repository/))
Uncaught exception: Failure("\"chown\" \"-R\" \"1000:1000\" \"/Users/mac1000\" failed with exit status 1")
2022-08-06 00:11.39: Job failed: Failed: Internal error
```

**Comment by tmcgilchrist** [comment]
This should be fixed in obuilder with changes to [how snapshots are pruned](https://github.com/ocurrent/obuilder/pull/157) and the introduction of [ZFS snapshots](https://github.com/ocurrent/obuilder/pull/164) rather than rsync. Please re-open if you encounter this issue again.
