### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/obuilder#121]
This is a tracking issue to cover getting OBuilder working with Windows and introducing support for Windows builds into [ocaml-ci](https://github.com/ocurrent/ocaml-ci) and [opam-repo-ci](https://github.com/ocurrent/opam-repo-ci)

## The Idea (as it relates to OBuilder)
The two core components of OBuilder are the Sandbox and the Store, the initial Windows support will use Docker for Windows to provide both. The Sandbox is provided by a running Windows container using either HyperV or Process isolation, and the store is using docker images.

Incomplete list of tasks:
 - [ ] Docker backend https://github.com/ocurrent/obuilder/pull/75
 - [ ] Docker & Windows prerequisites https://github.com/ocurrent/obuilder/pull/116
 - [ ] Add support for Docker/Windows spec  https://github.com/ocurrent/obuilder/pull/117
 - [ ] Add ocluster support for Windows https://github.com/ocurrent/ocluster/pull/143
 - [ ] Support Windows builds in ocaml-ci
 - [ ] Support Windows builds in opam-repo-ci
 
## Future work

 * Revisit using buildkit on Windows https://github.com/moby/buildkit
 * Investigate using HCS and runHCS tooling. https://techcommunity.microsoft.com/t5/containers/introducing-the-host-compute-service-hcs/ba-p/382332

**Comment by MisterDA** [comment]
moved to #123.

**Comment by MisterDA** [comment]
Moved to #123.
