### ISSUE TITLE
MacOS Support 

### ISSUE THREAD

**Issue by patricoferris** [ocurrent/obuilder#57]
This is a tracking issue (and will likely be updated) for getting OBuilder running with MacOS, there are quite a few moving parts which I'm currently holding in my head so it would be good to write them down and form a checklist of outstanding/resolved issues. 

### The Idea (as it relates to OBuilder)

The two core components of OBuilder are the Sandbox and the Store, as has been tested for MacOS Catalina, the ZFS backend works well for MacOS so we'll use that (although note the slight change further down). I have actually implemented most of the todos in the following list, but I think it makes it more manageable to split everything up into separate units to make the reviewing and PR process more manageable. 

Note we are now targeting macOS Monterey using user isolation and rsync backend. The ZFS backend was unstable and needs further investigation.

TODOs: 

 - [x] Improve the interface for sandboxes by separating out configurable values and providing a `cmdliner` value for based on the configuration parameters for a sandbox. This also means moving functionality currently in `lib/build` into the Sandbox like initialisation -- #58.
 - [X] Support different sandboxes depending on the OS of the host by using dune's select feature. Implemented in 193184a8d775a38e0918af59d2bbd0ec0c7c452f
 - [ ] Update the spec format to support additional information in the `(from ...` stage (this might not be necessary given the dune select todo as the choice is not at runtime and it is up to the sandbox implementation to provide meaning to the `from` stage).
 - [ ] Add some additional information as to the location of the ZFS volume (in MacOS it seems to always go in `/Volumes/tank` whereas OBuilder currently just looks at the root `/`)
 - [x] Implementation of the MacOS Sandbox using users as the unit of isolation instead of containers. https://github.com/ocurrent/obuilder/pull/122
 - [x] Add stress test for rsync on macOS 
 - [ ] Add stress test for ZFS on macOS
 - [ ] Support multiple user accounts on macOS
 - [ ] Add support to ocaml-ci https://github.com/ocurrent/ocaml-ci/pull/560

This will all have to integrated upstream with OCluster, OCaml-CI etc. too. Again, I've also tried this locally, so it seems like this list of todos is the right starting point. 

### Misc.

The other big piece to getting MacOS working is the FUSE filesystem for redirecting `/usr/local` to the user's home directory. This code is separate and contained in [obuilder-fs](https://github.com/patricoferris/obuilder-fs).

**Comment by tmcgilchrist** [comment]
Converting this to a [GH Project](https://github.com/orgs/ocurrent/projects/2/views/1) with the current setup documented in [macos-infra](https://github.com/ocurrent/macos-infra).
