### ISSUE TITLE
ZFS cannot promote: not a cloned filesystem

### ISSUE THREAD

**Issue by patricoferris** [ocurrent/obuilder#89]
An issue to track the current bug we are seeing on the Github runner with ZFS where during the stress test we get the following error:

```
+ opam exec -- dune exec -- ./stress/stress.exe zfs:zfs
cannot promote 'zfs/cache-tmp/0-c-c1': not a cloned filesystem
stress: internal error, uncaught exception:
        (Failure
          "\"sudo\" \"zfs\" \"promote\" \"zfs/cache-tmp/0-c-c1\" failed with exit status 1")
```

Note, previously on Travis builds this was working (with the same version of ZFS): https://travis-ci.org/github/ocurrent/obuilder/builds/768095520 and the stress test works with an older version of ZFS I've tried locally. Setting the stress test to output debug logs also suggests all of the `zfs` commands leading up to this call to `promote` are identical so I'm wondering if there is some weird github runner issue happening here. I'll see if I can update to the right version locally to see if that shows the bug.

**Comment by patricoferris** [comment]
Might be related to https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5972997.html

**Comment by patricoferris** [comment]
Looks like that is the issue and there doesn't seem to be any answer as to how to fix it... Using a third-party ppa is not an ideal solution but it shows (I think) that this is the problem https://github.com/patricoferris/obuilder/runs/4324615404?check_suite_focus=true

**Comment by talex5** [comment]
I think using a PPA is fine to get the CI passing. And maybe link to the issue from the error message?
