### ISSUE TITLE
Git lock failure

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/obuilder#96]
```
Building on cree.ocamllabs.io
fatal: Unable to create '/var/cache/obuilder/ocluster/git/opam-repository.git-b322f7b18d276db68487afc3dfc5a5befdd45818/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git-reset failed with exit-code 128
```
e.g. https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/fac594542e6e3fb469687d23f9ebe25982ab36c7/variant/opam-2.0,compilers,4.12,solo5-elftool.0.1.0

**Comment by talex5** [comment]
Probably just this again: https://github.com/ocurrent/ocluster/issues/115

**Comment by kit-ty-kate** [comment]
It happened again: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/05d575c1fe9cac3e1fd717d61936a03d27d7e68b/variant/opam-2.1,extras,nnp,libbinaryen.104.0.0

**Comment by tmcgilchrist** [comment]
And again https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c58c3f18c25359b70e1c8d7e00a5cd6530287fe0/variant/macos,macos-homebrew-ocaml-4.14-arm64,tezt.3.0.0

**Comment by kit-ty-kate** [comment]
See also https://github.com/ocurrent/opam-repo-ci/issues/202#issuecomment-1406727295

@talex5 are we using `Lwt.cancel` for anything at this level?

**Comment by talex5** [comment]
> @talex5 are we using Lwt.cancel for anything at this level?

Unlikely. I try to avoid it.

But I don't see what this issue has to do with OBuilder anyway. OCluster only passes a temporary copy of the git repository to OBuilder, so if it's broken then it's OCluster's fault (e.g. https://github.com/ocurrent/ocluster/issues/115).
